services:
  web:
    image: php:8.2-apache
    ports: 
      - 8080:80
    volumes:
      - ./app/:/var/www/html/
    links:
      - db:db
    networks:
      net:

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postdba 
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports: 
      - 5432:5432
    networks:
      net:

  dba: 
    image: adminer
    restart: always
    ports: 
      - 8081:8080
    networks:
      net:
    links:
      - db:db

networks:
  net:

volumes:
  pgdata:




